# Generated by Django 4.2 on 2023-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projeto", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=100)),
                ("longitude", models.CharField(max_length=100)),
                ("tir_media", models.CharField(max_length=100)),
                ("total_captado", models.CharField(max_length=100)),
                ("vgv", models.CharField(max_length=100)),
            ],
        ),
    ]
